package:
  name: limes
  version: ""

source:
  git_rev:
  git_url: https://github.com/Tony-xy-Liu/Limes.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    -

about:
  home: